"""
Initialize database and create all tables.

Startup sequence:
1. Create database tables
2. Migrate fixture data (users, orgs, teams, projects, etc.)
3. Optionally generate additional data if GENERATE_ADDITIONAL_DATA=1 is set
"""

import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.session import _get_seed_engine
from app.db.base import Base

# Import all models to register them with Base
from app.models import User, Email, EmailRecipient, Label, ThreadLabel, Attachment, Thread, SavedSearch, EmailTemplate

engine = _get_seed_engine()


def init_db():
    """Create all tables"""
    print("Creating database tables...")
    Base.metadata.create_all(bind=engine)
    print("✅ Database initialized successfully!")


def migrate_fixture_data():
    """
    Migrate fixture data from JSON files to the database.

    This must run BEFORE data generation to ensure fixture data exists
    and the data generator can reference it.
    """
    print("\n📦 Migrating fixture data...")

    # Import and run migrate_data
    from scripts.migrate_data import main as migrate_main

    try:
        migrate_main()
        print("✅ Fixture data migration completed!")
    except Exception as e:
        print(f"⚠️  Fixture migration warning: {e}")
        # Don't fail completely - tables may already have data


def _is_data_generated() -> bool:
    """Check if data has already been generated by looking for marker table."""
    from sqlalchemy import text
    with engine.connect() as conn:
        result = conn.execute(text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
            "WHERE table_name = '_data_generator_marker')"
        ))
        return result.scalar()


def _mark_data_generated():
    """Create marker table to indicate data generation is complete."""
    from sqlalchemy import text
    with engine.connect() as conn:
        conn.execute(text(
            "CREATE TABLE IF NOT EXISTS _data_generator_marker "
            "(generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
        ))
        conn.execute(text("INSERT INTO _data_generator_marker DEFAULT VALUES"))
        conn.commit()
    print("✅ Data generation marker set.")


def _get_psycopg2_connection_string() -> str:
    """
    Build a psycopg2-compatible connection string for the template database.
    Uses the same logic as app.database._get_seed_engine().
    """
    from sqlalchemy.engine import make_url
    from app.core.config import DATABASE_URL, POSTGRES_TEMPLATE_DB

    # Build URL for template database
    template_url = make_url(DATABASE_URL).set(database=POSTGRES_TEMPLATE_DB)

    # IMPORTANT: In SQLAlchemy 2.x, `str(url)` hides the password ("***").
    # We must render a real connection string for psycopg2, but keep logs redacted.
    real_url_str = template_url.render_as_string(hide_password=False)
    safe_url_str = template_url.render_as_string(hide_password=True)

    # Convert to psycopg2 format (remove +psycopg2 from dialect)
    # SQLAlchemy: postgresql+psycopg2://user:pass@host:port/db
    # psycopg2:   postgresql://user:pass@host:port/db
    if "+psycopg2" in real_url_str:
        real_url_str = real_url_str.replace("+psycopg2", "")
    if "+psycopg2" in safe_url_str:
        safe_url_str = safe_url_str.replace("+psycopg2", "")

    return real_url_str, safe_url_str


def generate_additional_data():
    """
    Generate additional fake data using the data_generation module.

    The data generator will:
    - Query existing data from the database (fixture data)
    - Only generate NEW records to reach the requested totals
    - Assign generated records (like tickets) to existing entities (like projects)

    Controlled by environment variables:
    - GENERATE_ADDITIONAL_DATA: Set to "1" to enable
    - DATA_GENERATOR_PARAMS: Space-separated CLI arguments (e.g., "--rows tickets=1000 --seed 42")
    """
    if os.getenv("GENERATE_ADDITIONAL_DATA") != "1":
        print("ℹ️  Skipping data generation (GENERATE_ADDITIONAL_DATA not set to 1)")
        return

    # Check if data was already generated (idempotency)
    if _is_data_generated():
        print("ℹ️  Data already generated (marker table exists), skipping.")
        return

    print("\n📊 Generating additional data...")

    # Get connection string for template database
    connection_string, safe_connection_string = _get_psycopg2_connection_string()

    # Parse additional parameters from environment
    params_str = os.getenv("DATA_GENERATOR_PARAMS", "")

    # Build CLI arguments - use postgres format with --use-db to:
    # 1. Query existing data from DB (fixture data)
    # 2. Write directly to postgres (uses fixed postgres_writer with proper enum handling)
    cli_args = [
        "--format", "postgres",
        "--use-db", connection_string,
    ]

    # Add any additional params from environment
    if params_str:
        import shlex
        cli_args.extend(shlex.split(params_str))

    # Log args with password redacted
    cli_args_for_log = list(cli_args)
    try:
        use_db_idx = cli_args_for_log.index("--use-db")
        cli_args_for_log[use_db_idx + 1] = safe_connection_string
    except ValueError:
        pass
    print(f"Data generator args: {cli_args_for_log}")

    # Import and run data generator
    try:
        # Add data_generation to path if not already there
        data_gen_path = Path(__file__).parent.parent.parent / "data_generation"
        if str(data_gen_path) not in sys.path:
            sys.path.insert(0, str(data_gen_path.parent))

        from data_generation.cli import main as data_gen_main

        exit_code = data_gen_main(cli_args)

        if exit_code == 0:
            _mark_data_generated()
            print("✅ Data generation completed successfully!")
        else:
            print(f"❌ Data generation failed with exit code {exit_code}")
    except Exception as e:
        print(f"❌ Data generation error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    init_db()
    migrate_fixture_data()
    generate_additional_data()
