[feature_toggles]
provisioning = true

[paths]
; This is devenv/dev-dashboards and conf/provisioning by default.
permitted_provisioning_paths = grafana/ | /etc/grafana/provisioning/

[log]
level = warn
