{
 "title": "Backend Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "P95 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_server_duration_milliseconds_bucket[1m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 URLs by average latency (ms)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  (\n    sum by (http_target) (\n      rate(http_server_duration_milliseconds_sum{http_target!=\"\"}[5m])\n    )\n  /\n    sum by (http_target) (\n      rate(http_server_duration_milliseconds_count{http_target!=\"\"}[5m])\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 URLs by average requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n  10,\n    sum by (http_target) (\n      increase(http_server_duration_milliseconds_count{http_target!=\"\"}[1m])\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}