{
 "title": "Frontend Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "P95 Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_request_duration_milliseconds_bucket[1m])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 URLs by latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  (\n    sum by (path) (\n      increase(http_request_duration_milliseconds_sum{path!=\"\"}[$__range])\n    )\n    / (\n    sum by (path) (\n      increase(http_request_duration_milliseconds_count{path!=\"\"}[$__range])\n    ) > 0)\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 URL by Request Counts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topK(10, sum by (path) (\n  increase(http_request_duration_milliseconds_count{path!=\"\",path!~\".+otel-metrics\"}[$__range])\n))\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}